### ISSUE TITLE
Matching only a subset

### ISSUE THREAD

**Issue by Enchiridion** [lezhnev74/pasvl#11]
What's the correct/best way to only match a subset of the array's keys and ignore the rest?

For example in the arrray `[ 'foo' => 'zoo', 'bar' => 42, 'baz' => true ]`, I only care about validating the values of `foo` and `bar` and don't care about `baz` or any other entries that may appear later.

**Comment by lezhnev74** [comment]
from the top of my head, have you tried 
```
[
  "foo" => "zoo",
  "bar" => 42,
  "baz" => true,
  "*" => ":any"
]
```

**Comment by Enchiridion** [comment]
That worked exactly as I needed, thanks!

I didn't think to try '*' as it was only used with arrays in the examples, thought it was just for sub-patterns.
