### ISSUE TITLE
object(nullable) with subvalidators fails

### ISSUE THREAD

**Issue by corrigang** [lezhnev74/pasvl#6]
Love the library; just started using hit.
However, encountered this issue - have a validator pattern like:
$ref = ":object(nullable) :instance(\My\Class\Name)"
Which will always fail if the object actually is null (it still checks for the instance type, even though object is set to Nullable.

I subclassed ObjectValidator, but looking at the validators, this may be an issue throughout the library?

[NullobjectValidator.txt](https://github.com/lezhnev74/pasvl/files/2393123/NullobjectValidator.txt)

**Comment by lezhnev74** [comment]
Hi @corrigang! 
sorry for a late response, busy times.  
Thank you for reporting! Will take a look at this issues asap.

**Comment by lezhnev74** [comment]
This is a bit late, sorry for that. 
I looked at the problem and hopefully fixed that with the newest release `0.5.6`.

p.s. the problem was that the `nullable` in a pattern `:validator(nullable)` was actually passed as a string instead of boolean and we needed to convert it to the boolean first in the code.

p.s. any argument

**Comment by lezhnev74** [comment]
Let me expand on this nullable subject.

Each pattern consists of a main validator (the first one) and subvalidators: `:object :instance(\stdClass)`.

These validators are mapped directly to class' methods. The main validator maps to `__invoke` and subvalidators map to corresponding methods. These methods are called coherently on by one from the same object instance. So to make sure the next method knows about the nullable flag you have to maintain the state.

Please review the class at https://github.com/lezhnev74/pasvl/blob/master/src/Validator/ObjectValidator.php
