### ISSUE TITLE
Simple regex doesn't match

### ISSUE THREAD

**Issue by JuGid** [lezhnev74/pasvl#7]
Hi,

I'm trying to use your library that's really cool and interesting for the project I'm doing. First time using it, I'm facing this issue.

I have this $pattern (comes from a var_dump($pattern)) : 
```
array(1) {
  ["go"]=>
  string(36) ":string :regexp("%^(https?:\/\/)%i")"
}
```

And this array (as $this->step) : 

```
array(1) {
  ["go"]=>
  string(25) "https://www.wikipedia.org"
}
```

when I use this code : 

```
private function validate() {
        $pattern = $this->getPattern();
        $builder = ValidatorBuilder::forArray($pattern);
        $validator = $builder->build();
        $value = true;

        try {
            $validator->validate($this->step);
        } catch (ArrayFailedValidation $e) {
            echo "Step [". key($this->step)  ."] is not a valid step. Watch out the syntax pattern.\n";
            echo "[Error details] " . $e->getMessage() . "\n";
            $value = false;
        }

        return $value;
    }
```

But it returns this lines : 

```
Step [go] is not a valid step. Watch out the syntax pattern.
[Error details] Data value [https://www.wikipedia.org] matched no pattern at root level
```

I tried using preg_match("%^(https?://)%i", 'https://wikipedia.fr'); and it returns 1 (so, true). 
I don't know what's wrong with that. Can you help me ?

Regards,

**Comment by JuGid** [comment]
Ok, my problem was from delimiters. As a PHP user I tried the regex as this : 
`:regexp("%^(https?:\/\/)%i")`
But the thing is that I assume you don't accept delimiters in regexp, so my regex has to be : 
`:regexp("^(https?:\/\/)")`

I was wrong, but I let this open as an hint, maybe. And because I want the author to see it to tell me if it's normal or not.

Thanks again for this library !

**Comment by lezhnev74** [comment]
Hey @JuGid, this is a good catch. I understand your confusion, you make me thinking if the `regexp` should not assume delimiters (and therefore allow one to provide flags like `i`).

**Comment by JuGid** [comment]
The library already makes the job required for regex. It's not really blocking me, only the syntax should be explained (for flags only, as a hint ?). Maybe there is a way to do it already ?

**Comment by lezhnev74** [comment]
I've added a section `Built-in Rules` with hints (including for `regexp`). If you want to have it with delimiters and flags, feel free to submit a PR and modify how regexp sub-rule works, if not then let's call it done.
