### ISSUE TITLE
Validation failed with number

### ISSUE THREAD

**Issue by JuGid** [lezhnev74/pasvl#9]
Hi,

I'm facing an issue I don't really understand. I have this pattern : 

```
array(1) {
  'loop' =>
  array(2) {
    'count' =>
    string(26) ":string :regexp("/(\d)*/")" also tried ":number :int"
    'sub' =>
    string(7) ":string"
  }
}
```

For this array : 

```
array(1) {
  'loop' =>
  array(2) {
    'count' =>
    string(1) "5"
    'sub' =>
    string(13) "create-cookie"
  }
}
```

PASVL always returns an error and I don't really know why. It's an exception that says : `Data value [5] matched no pattern at level [loop]`. This is the whole stack trace (only PASVL concern) : 

```
[Error details] Data value [5] matched no pattern at level [loop]
PASVL\Validation\Problems\DataValueMatchedNoPattern: Data value [5] matched no pattern at level [loop] in /AutoMate/vendor/lezhnev74/pasvl/src/Validation/Problems/ArrayFailedValidation.php:14
Stack trace:
#0 /AutoMate/vendor/lezhnev74/pasvl/src/Validation/Problems/DataValueMatchedNoPattern.php(22): PASVL\Validation\Problems\ArrayFailedValidation::make(Array, 'Data value [5] ...')
#1 /AutoMate/vendor/lezhnev74/pasvl/src/Validation/ArrayValidator.php(97): PASVL\Validation\Problems\DataValueMatchedNoPattern::fromData('5', Array)
#2 /AutoMate/vendor/lezhnev74/pasvl/src/Validation/ArrayValidator.php(55): PASVL\Validation\ArrayValidator->validateArrayLevel(Array, Array)
#3 /AutoMate/vendor/lezhnev74/pasvl/src/Validation/ArrayValidator.php(89): PASVL\Validation\ArrayValidator->matchValue(Array, Array)
#4 [internal function]: PASVL\Validation\ArrayValidator->PASVL\Validation\{closure}('loop')
#5 /AutoMate/vendor/lezhnev74/pasvl/src/Validation/ArrayValidator.php(95): array_filter(Array, Object(Closure))
#6 AutoMate/vendor/lezhnev74/pasvl/src/Validation/ArrayValidator.php(55): PASVL\Validation\ArrayValidator->validateArrayLevel(Array, Array)
#7 /AutoMate/vendor/lezhnev74/pasvl/src/Validation/ArrayValidator.php(41): PASVL\Validation\ArrayValidator->matchValue(Array, Array)
#8 /AutoMate/src/Scenario/Transformer/AbstractTransformer.php(80): PASVL\Validation\ArrayValidator->validate(Array)
```

It seems that the pattern matches the array right... But it doesn't.

**Comment by JuGid** [comment]
I have investigate a bit more, and it's caused by the subrule ":int" that does not detect 5 as an int or '5' also (btw it's a string). Most of parser parse [count: 5] as ["count" => "5"] so you don't have to use ":number :int" as it uses is_int() from php to validate but ":number" or ":string" only.

Is it relevant to propose a PR that also convert '5' to 5 with intval() when ":number :int" is used with a string like '5' or '5678' ?

**Comment by lezhnev74** [comment]
Hey @JuGid ! Yeah, with PHP it is not always clear how to deal with type coercion. String can be coerced to int or float and back again. Can we say that `"5"` is equivalent to `5`? In PHP... probably, in general those are data of different types.

Let's review your example:
1. the pattern `:number :int` won't match `"5"`, because it only matches integers (hence the sub-rule `:int`).
2. however, simple `:number` would match `"5"` or `5` or `5.0`
3. the pattern `:string :regexp("/(\d)*/")` matches `"5"` only (hence `:string` rule)

As a reference, this test passes (see the image).
![image](https://user-images.githubusercontent.com/10206110/108170378-eda4fa80-711b-11eb-962c-d4cbfa361496.png)

> Is it relevant to propose a PR that also convert '5' to 5 with intval() when ":number :int" is used with a string like '5' or '5678' ?

Since this library is purely for PHP (with its dynamic nature), I think the PR makes sense.

**Comment by JuGid** [comment]
> Let's review your example:
> 
> 1. the pattern `:number :int` won't match `"5"`, because it only matches integers (hence the sub-rule `:int`).
> 2. however, simple `:number` would match `"5"` or `5` or `5.0`
> 3. the pattern `:string :regexp("/(\d)*/")` matches `"5"` only (hence `:string` rule)

This is what I found when I made my tests. PHP can presents some weird cases since 'a' == 0 returns true, et 'f' == 0 returns true too.
What I can propose is juste make a verification with is_numeric. If false, throw an Exception, else, continue with intval.

**Comment by lezhnev74** [comment]
There is another way for you, use a compound rule: `:string :regexp("/(\d)*/") or :number :int` which matches `5` and `"5"`.

**Comment by JuGid** [comment]
Yes, that's a good solution, but `:string :regexp("/(\d)*/")` does not match "5" weirdly... As I did in my first test.

**Comment by lezhnev74** [comment]
ok, let's review your failing test. Can you push it?

**Comment by JuGid** [comment]
I can post a simple test that glob each one I did : 

```
<?php

require __DIR__.'/vendor/autoload.php';

use PASVL\Validation\ValidatorBuilder;

$patterns = [
    [
        'loop'=> [
            'count' => ':string :regexp("/(\d)*/")'
        ]
    ],
    [
        'loop'=> [
            'count'=>':number :int'
        ]
    ],
    [
        'loop'=> [
            'count'=>':string :regexp("/(\d)*/") or :number :int'
        ]
    ],
    [
        'loop'=> [
            'count'=>':string'
        ]
    ],
    [
        'loop'=> [
            'count'=>':number'
        ]
    ]
];

$array = ['loop'=> [
        'count'=> '5'
    ]
];

foreach($patterns as $pattern) {
    try{
        $builder = ValidatorBuilder::forArray($pattern);
        $validator = $builder->build();
        $validator->validate($array);
        echo 'Test pass' . "\n";
    }catch(\Exception $e) {
        echo $e->getMessage() . "\n";
    }
}
```

Console output : 

```
Data value [5] matched no pattern at level [loop]
Data value [5] matched no pattern at level [loop]
Data value [5] matched no pattern at level [loop]
Test pass
Test pass
```

**Comment by lezhnev74** [comment]
Ok, I need data as well to understand what has happened, or you can actually push a failing test to the `ArrayValidatorTest`.

**Comment by lezhnev74** [comment]
Ah I see there is a small `$array` in the code sample, let me review it.

**Comment by lezhnev74** [comment]
Very interesting, my output is:
```
Test pass
Data value [5] matched no pattern at level [loop]
Test pass
Test pass
Test pass
```

The second failure is expected as it applied rule `:number :int` on `'5'`.
I run `PHP 7.4.15`, what is your version?

**Comment by JuGid** [comment]
On the MacOS, I have a `PHP 7.3.10` (Wow, I have to update that... I'm so late)

**Comment by lezhnev74** [comment]
are you positive you are using the latest `1.0.0` release?

**Comment by JuGid** [comment]
Oh ok... I updated PASVL from 0.6.4 to 1.0.0 and the tests pass now, I did not see the new release... My bad. 

Going to change my patterns now to new valuable patterns that matches the reality...
